# Introduction to numpy

In [1]:
import numpy as np

access elements

In [3]:
x=np.arange(10) 
print(x)
print(x[:5]) 
print(x[5:])
print(x[4:7]) 
print(x[::2]) 
print(x[1::2]) 
print(x[::-1])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


view

In [5]:
a=np.arange(10) 
print(a)
b=a[::2]
print(b) 
print(np.may_share_memory(a,b)) 
b[0]=12
print(b,a)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True
[12  2  4  6  8] [12  1  2  3  4  5  6  7  8  9]


subarray and copy

In [7]:
a = np.arange(10)
print(a)
c = a[::2].copy() # force a copy print(c)
c[0] = 12
print(c) 
print(np.may_share_memory(a,c))

[0 1 2 3 4 5 6 7 8 9]
[12  2  4  6  8]
False


computation

In [9]:
x = np.arange(10) 
print("x= ", x) 
print("x+5=", x+5) 
print("x=5=", x-5) 
print("x*2=", x*2) 
print("x/2=", x/2) 
print("x//2=", x//2)

x=  [0 1 2 3 4 5 6 7 8 9]
x+5= [ 5  6  7  8  9 10 11 12 13 14]
x=5= [-5 -4 -3 -2 -1  0  1  2  3  4]
x*2= [ 0  2  4  6  8 10 12 14 16 18]
x/2= [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
x//2= [0 0 1 1 2 2 3 3 4 4]


In [10]:
x = np.array([-3+4j, 3-4j, 0-3j]) 
print(np.abs(x)) 
x = np.array([-2, 3, -4, 5, -6]) 
print(np.abs(x))
x=[1, 2, 3]
print("x=", x) 
print("e^x=", np.exp(x)) 
print("2^x=", np.exp2(x)) 
print("2^x=", np.power(2,x)) 
print("3^x=", np.power(3,x))

[5. 5. 3.]
[2 3 4 5 6]
x= [1, 2, 3]
e^x= [ 2.71828183  7.3890561  20.08553692]
2^x= [2. 4. 8.]
2^x= [2 4 8]
3^x= [ 3  9 27]


In [11]:
x = np.arange(1, 5) 
print(x)
print("Sum=", np.add.reduce(x)) 
print("Product=", np.multiply.reduce(x)) 
print("Sums=", np.add.accumulate(x)) 
print("Products=", np.multiply.accumulate(x))

[1 2 3 4]
Sum= 10
Product= 24
Sums= [ 1  3  6 10]
Products= [ 1  2  6 24]


In [12]:
M=np.random.randint(1, 100, size=(3,4)) 
print(M)
print(np.sum(M)) 
print(np.sum(M, axis=0)) 
print(np.sum(M, axis=1))

[[78 32 18 82]
 [59  5 20 30]
 [50 49 48 40]]
511
[187  86  86 152]
[210 114 187]
